GameBoard
Duchyna1/pts24-java pull request #72
Opened 2024-11-13 10:49 UTC by Duchyna1

resolves #31

2024-11-14 10:55 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/ToolMakerHutsFields.java
> +        return "ToolMakerHutsFields:\n"
To JSON

2024-11-14 10:55 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/VariableBuilding.java
> +        return "Number of resources required: " + numberOfResources + ", exact number of types required: " + numberOfResourcesTypes + "\n";
To JSON

2024-11-14 10:59 UTC, Duchyna1 commented on src/main/java/sk/uniba/fmph/dcs/game_board/VariableBuilding.java
> +        return "Number of resources required: " + numberOfResources + ", exact number of types required: " + numberOfResourcesTypes + "\n";
Čo znamená to JSON?

2024-11-14 11:05 UTC, Stanko2 requested changes

2024-11-14 11:05 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/SimpleBuilding.java
> +        return "Required resources: " + requiredResources.toString() + "\n";
To JSON

2024-11-14 11:05 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/ArbitraryBuilding.java
> +        return "Number of arbitrary resources required: " + numberOfResources + "\n";
To JSON

2024-11-14 11:06 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/VariableBuilding.java
> +        return "Number of resources required: " + numberOfResources + ", exact number of types required: " + numberOfResourcesTypes + "\n";
Pozri `GamePhaseController.java`

2024-11-16 10:12 UTC, Stanko2 approved these changes

2024-11-16 14:00 UTC, Duchyna1 commented
@Stanko2 @johankogoodvibes môžem mergovat?

2024-11-16 15:05 UTC, johankogoodvibes commented
Asi hej

2024-11-16 16:29 UTC, merged