GameBoard CivilisationCards
Duchyna1/pts24-java pull request #74
Opened 2024-11-13 17:23 UTC by johankogoodvibes

resolves #23 
resolves #16 
resolves #17 
resolves #18

2024-11-14 11:29 UTC, Stanko2 requested changes

2024-11-14 11:29 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/RewardMenu.java
> +        return HasAction.WAITING_FOR_PLAYER_ACTION;
If `player` is the last player left perform the action automatically

2024-11-14 11:29 UTC, Stanko2 commented on src/main/java/sk/uniba/fmph/dcs/game_board/GetSomethingFixed.java
> +    public boolean performEffect(final Player player, final Effect choice) {
Ignore choice and put everything to player

2024-11-16 10:10 UTC, Stanko2 approved these changes

2024-11-16 13:59 UTC, Duchyna1 commented
@johankogoodvibes @Stanko2 môžem mergnut? Či ešte niečo?

2024-11-16 15:05 UTC, johankogoodvibes commented
Asi hej

2024-11-16 16:37 UTC, merged